baseURL = "https://chandan5362.github.io/"
languageCode = "en-us"
title = "Chandan's Blog"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Chandan Roy - All rights reserved"
enableEmoji = true
disqusShortname = "chandan5362"
googleAnalytics = "G-DNTXE8FETV"

[params]
  logo = "/images/logo.png"
  description =""
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Chandan Kumar Roy"
  thumbnail = "/images/author.png"
  description = "Author of this blog."

[params.index]
  picture = "/images/author.png"
  title = "Chandan Kumar Roy"
  subtitle = "Data Science and Machine Learning"
  mdtext = '''
I am a 4th year undergraduate at Indian Institute of information Technology Sricity, Chittoor\
**(Computer Science and Engineering with specialization in Data Science)**

## Skills
Statistics\
Machine Learning\
Deep Learning\
Computer Vision\
Natural language Processing\
Data Visualization & story telling

 **Please find my resume here**, [click here](https://drive.google.com/file/d/16mlTly4vQOASLNt0Erva0jtLfQ9i1cUO/view?usp=sharing)
'''
  alertbar = false

[params.social]
  github = "chandan5362"
  linkedin = "chandan5362"
  medium = "chandan5362"
  twitter = "Chandan15771793"
  instagram = "chandan_5362"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"

[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"


[[menu.main]]
    name = "ML Glossary"
    identifier = "ml glossary"
    weight = 200
    url = "/glossary"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

